# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    open = false;
    modesetting.enable = true;
    powerManagement.enable = false;
    prime = {
      sync.enable = true;
      nvidiaBusId = "PCI:0:1:0";
      intelBusId = "PCI:0:0:2";
    };
  };
  services.xserver.videoDrivers = [ "nvidia" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3e5cbe20-6a4a-4d73-8950-1c1b06feae30";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-06feafec-e8a4-45db-80c7-71615a28d529".device =
    "/dev/disk/by-uuid/06feafec-e8a4-45db-80c7-71615a28d529";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9690-341E";
    fsType = "vfat";
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/604d01be-d04c-45f3-a860-0ad1e8b89e5a"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
}
